# Generated by Django 4.2 on 2023-12-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DockMac",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("allocation", models.CharField(blank=True, max_length=255, null=True)),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                ("mac", models.CharField(blank=True, max_length=255, null=True)),
                ("metastring", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "dock_mac",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocation", models.CharField(blank=True, max_length=255, null=True)),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mac",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("metastring", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "mac",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AllocationType", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DeviceName", models.CharField(max_length=30)),
            ],
        ),
    ]
